name: Deploy DN6 Web Ubuntu Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: <your-app-name-here> 

jobs:
  build-and-deploy:
    name: 'Build And Deploy to Azure'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set up .NET Core'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: 'Install Dependencies'
        run: dotnet restore
      - name: 'Build with dotnet'
        run: dotnet build --configuration Release
      - name: 'Test'
        run: dotnet test --no-restore --verbosity normal
      - name: 'dotnet publish'
        run: | 
          dotnet publish -c Release -o dotnetcorewebapp
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.YOUR_APP_PUBLISH_PROFILE_SECRET_HERE }}  
          package: './dotnetcorewebapp' 
