name: Deploy SimpleWeb To Test on merge to dev branch

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: simple-web-20220607-blg 
  AZURE_WEBAPP_SLOT: Test

jobs:
  build-and-deploy:
    name: 'Build And Deploy to Azure'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set up .NET Core'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: 'Install Dependencies'
        run: dotnet restore
      - name: 'Build with dotnet'
        run: dotnet build --configuration Release
      - name: 'Test'
        run: dotnet test --no-restore --verbosity normal
      - name: 'dotnet publish'
        run: | 
          dotnet publish -c Release -o dotnetcorewebapp
      - name: 'Deploy to Azure WebApp'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name: ${{ env.AZURE_WEBAPP_SLOT }}
          publish-profile: ${{ secrets.PUBLISH_PROFILE_SIMPLEWEB_TEST }}  
          package: './dotnetcorewebapp' 
